variable enabled {
  description = "Set to false (default) to prevent from creating any resources"
  type        = bool
  default     = false
}

variable build_id {
  description = "Autogenerated. Used for placing commit id into the state file from scm"
  type        = string
  default     = ""
}
