variable "enabled" {
  description = "Set to false to prevent from creating any resources"
  type        = bool
  default     = false
}

variable "environment" {
  description = "Which environment to use to deploy this stack. Can be either dev, stg or prd"
  type        = string
  #default     = "unknown"
}

variable "tags" {
  type        = map(string)
  description = "Tags"
  default     = { By_terraform = true }
}

variable "build_id" {
  description = "Autogenerated. Used for placing commit id into the state file from scm"
  type        = string
  default     = ""
}

variable "whoami" {
  description = "Autogenerated. Used for placing CI comments on gh actions"
  type        = string
  default     = "unknown"
}
